### ISSUE TITLE
z is atomic number in SamplingE0?

### ISSUE THREAD

**Issue by HeConnor** [federicocampo/Positron-Range#7]
Hello, 
     I have been using your code to study the positron range of different nuclei, and I have a question about a variable in the code.

```python
def SamplingE0(isotope):

    if isotope == 'F18':
        z = 10

```
z is atomic number ? z=9?

Furthermore, I would like to ask if your code implementation was referenced from any literature? I am interested in understanding the overall process.

Looking forward to any response from you.

best regrads,

Connor

**Comment by federicocampo** [comment]
Hi Connor, 
Thank you for using my code :)

Yes, you're right, that z should be the atomic number, I don't know why 2 years ago I shifted all my z ->z+1, there's no reason to do that.

All the theory I used to create the code comes from W.R. Leo - Techniques for nuclear and particle physics (pages 20 to 30 more or less). 
I also attach a document I created to summarize the main step of the code and the theory behind (It's in Italian, I only have this version)
[Positron range - Campo.pdf](https://github.com/federicocampo/Monte-Carlo-Positron-Range/files/11929021/Positron.range.-.Campo.pdf).

If you spot any other errors, please let me know, I published the code without double checking it.

Thank you, 
Best, 
Federico

**Comment by HeConnor** [comment]
Hello, Federico

​		Thank you for your reply.  These materials are very helpful!

​		Before reading the reference materials you provided, I have a new understanding of the meaning of 'z', but I'm not sure if it's correct.

**Beta decay**:

1. $\beta^-$ decay
   $$(Z, A)  \rightarrow (Z+1, A) + e^- + \overline{v}_e $$

2. $\beta^+$ decay
   $$(Z, A)  \rightarrow (Z-1, A) + e^+ + v_e $$

3. Electron Capture

   $$e^- + (Z, A)  \rightarrow (Z-1, A) + v_e $$




Best regrads,

Connor

**Comment by federicocampo** [comment]
Hi Connor,

Now I remember why I systematically put z->z+1, it would be correct if the traveling particles were electrons. 
In our simulation, all the isotopes decay $\beta^+$, so the emitted particle is a positron. 
I mixed some theory in the code, let me explain:

To sample from the energy distribution of the emitted particle, I use (among others) the function F_ze=F (z, E) where z should be the atomic number of the daughter nucleus.
In our case for example F18 -> O18 + $e^+$ + $\nu_e$, so the z variable should be the atomic number of oxygen (z=8).

The entire simulation though, is also valid for electrons (in some functions you can choose 'pos' or 'el', it will change some variables/sections of a function), and in that case, the daughter nucleus will be z = Z+1.

You can find a clear explanation of the positron range simulation in this paper https://iopscience.iop.org/article/10.1088/0031-9155/44/3/019 which also provides a brief explanation of the F(z, E) function.

Hope that helps, 
sorry for my previous misleading answer, 

Best, 
Federico
